monday: "http://www.otto-nagel-gymnasium.de/joomla158/plaene/KLmontag.htm"
tuesday: "http://www.otto-nagel-gymnasium.de/joomla158/plaene/KLdienst.htm"
wednesday: "http://www.otto-nagel-gymnasium.de/joomla158/plaene/KLmittwo.htm"
thursday: "http://www.otto-nagel-gymnasium.de/joomla158/plaene/KLdonners.htm"
friday: "http://www.otto-nagel-gymnasium.de/joomla158/plaene/KLfreita.htm"